---
name: deploy
on:
  workflow_run:
      workflows: [CI]
      branches: [main]
      types:
        - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/pba/namemelater
            git fetch origin main
            git reset --hard FETCH_HEAD
            git clean -d -f --exclude .env
            venv/bin/pip install -r requirements/main.txt
            (source '.env' && bash 'venv/bin/python -m aenrich upgrade')
            sudo /usr/bin/systemctl restart namemelater
            sleep 5
            /usr/bin/journalctl -u namemelater -q | tail
